### ISSUE TITLE
Unable to install in Atlantis neo

### ISSUE THREAD

**Issue by smdotdev** [endeavouros-team/EndeavourOS-calamares#10]
Here is the log

https://termbin.com/fbb9

**Comment by killajoe** [comment]
This is not the proper place to get help on installing.
Please consider to subscribe to the forum and asking for installer help there, this is for development only here.
But i see that you have an issue with getting packages installed, you may want to update mirrorlist before starting online install, and add some nearby countries.. you can also add US and Germany mirrors to the list, which will work in most cases.

**Comment by killajoe** [comment]
.. we have also a support chat at telegram:
https://t.me/Endeavouros

**Comment by smdotdev** [comment]
I was able to install with 21.4.
I registered myself on the forum, but there was some restrictions (even still not able to comment or post anything), so googled and found this place to be the most suitable to report calamares related errors, BTW thanks for awesome distro.

**Comment by killajoe** [comment]
could be an issue with network device also.. 
If you mind you can PM me at forum so i can check your account status

**Comment by smdotdev** [comment]
> If you mind you can PM me at forum so i can c

done
