### ISSUE TITLE
feature request: add XFS support

### ISSUE THREAD

**Issue by mabod** [endeavouros-team/EndeavourOS-calamares#15]
Can you please add XFS to the supported filesystems?

In `modules/partition.conf` it would look like this:

`availableFileSystemTypes:  ["ext4","btrfs","xfs"]`

**Comment by killajoe** [comment]
https://forum.endeavouros.com/t/why-is-the-default-fs-only-ext4-or-btrfs/23306/65

**Comment by killajoe** [comment]
https://github.com/endeavouros-team/EndeavourOS-calamares/commit/04d6b8b36035f85cd907defd54f0f00994cd9f4d
