### ISSUE TITLE
desktop request: wayfire

### ISSUE THREAD

**Issue by godalming123** [endeavouros-team/EndeavourOS-calamares#21]
Would it be possible to be able to select the wayfire desktop at install as I am having trouble installing it

**Comment by killajoe** [comment]
"select" ? you mean adding it.. this would need someone creating community edition for it.
What will be here to add:
https://github.com/EndeavourOS-Community-Editions
But it is not present on Arch Repository only on AUR and not maintained well there:
https://aur.archlinux.org/packages/wayfire

**Comment by godalming123** [comment]
What about installation from source

**Comment by godalming123** [comment]
And by select I mean having it in the installer as a desktop environment

**Comment by killajoe** [comment]
As i mentioned, for default installs we will not add anything like that, it could be possible as a Community Edition maintained by someone from the community. 
I know other distros have wayfire version already, but our dev ream is working on main installs ISO and Installer maintaining, and we are only a small team doing this as a hobby ;)
