### ISSUE TITLE
Endeavour OS - Calameres - Customization 

### ISSUE THREAD

**Issue by EbenezerJesuraj** [endeavouros-team/EndeavourOS-calamares#25]
Can i expect a future version where Endeavour-OS Features a Polybar Integration with i3wm.

(Similar to be found in Rick-Ellis config)

**Comment by killajoe** [comment]
this is not related in any way to installer and its configurations, it would belong here:
https://github.com/endeavouros-team/endeavouros-i3wm-setup

But as we want to stay basic and minimal for the default install options best would be to add a custom i3 version as Community Edition here:
https://github.com/EndeavourOS-Community-Editions
