### ISSUE TITLE
Enable ext4's fast_commit by default

### ISSUE THREAD

**Issue by RubenKelevra** [endeavouros-team/EndeavourOS-calamares#27]
I noticed that after installation on ext4 the fast_commit feature wasn't turned on.

I don't think there's any downside of doing this.

https://www.phoronix.com/scan.php?page=news_item&px=EXT4-Fast-Commit-Queued

**Comment by killajoe** [comment]
_Starting from the 5.10 kernel, ext4 may have a performance boost by enabling the fast_commit option:_ 

https://wiki.archlinux.org/title/Ext4#Enabling_fast_commit_in_existing_filesystems

Not sure if it is a good default.  and it is easy to enable on installed system if you want to use. 

It will need some more information and research before we blindly add this. 
I will add this to "after apollo release tasks"

**Comment by killajoe** [comment]
After research and discussion we think such option should be better documented in the wiki under an entry about tweaking the system or similar, as if it is enabled per default most user will not know about and never get knowledge on how to handle tweaking..

**Comment by RubenKelevra** [comment]
@killajoe I don't think there's any disadvantage by using fast_commit. LWN explains how this works:


> The fast-commit optimization is designed to work with applications using fsync() frequently to ensure data integrity. When we look at the fsync() and fdatasync() man pages, we see that those system calls only guarantee to write data linked to the given file descriptor. With ext4, as a side effect of the filesystem structure, all pending data and metadata for all file descriptors will be flushed instead. This creates a lot of I/O traffic that is unneeded to satisfy any given fsync() or fdatasync() call. 


A fast commit basically ensured to have minimum write IO for single fsyncs, but will have the same guarantees on data integrity.

The only reason this is not on by default is backward compatibility. I doubt that's an issue for the root partition of EndeavourOS users.
