### ISSUE TITLE
Ship with thermald service on

### ISSUE THREAD

**Issue by RubenKelevra** [endeavouros-team/EndeavourOS-calamares#28]
After installation I noticed that Endeavouros don't come with the thermald service. I think it makes sense to have this service installed and active, as long as there's an intel cpu detected, to avoid overheating:

https://wiki.archlinux.org/title/CPU_frequency_scaling#thermald

**Comment by killajoe** [comment]
these are not issues or Bugs you are reporting and also no commits or pull requests to the code. 
We usually do not discuss such questions here at GitHub and using forum or chat for it. 
Also EndeavourOS is not an optimized performance, ready to use Desktop installer.. we offer a minimal install with basic needed settings enabled only, read to start to setup as user like.

**Comment by RubenKelevra** [comment]
Yeah, this was more of a feature request. But depending on the hardware itself, it might be necessary to avoid possible overheating on intel notebooks. So I guess it's a potential issue - depending on the hardware.

So I was not sure, if this is a necessary and should be included. That's why I created a ticket.
