### ISSUE TITLE
Feature Request: Add warning to install zen-headers when booting on Nvidia non-free driver

### ISSUE THREAD

**Issue by purpl3F0x** [endeavouros-team/EndeavourOS-calamares#30]
Hello, recently I installed EndevourOS and along side it I installed the zen kernel. Although I forgot to tick it's headers. I have an Nvidia GPU and choose the proprietary drivers. The normal kernel would boot but the zen one obviously not cause the dkms didn't have the headers for it.
There should be a warning imo, either to select it automatically or use some kind of message. 

I'm not an experienced /regular Linux user and struggled to find what was the problem for the kernel not to boot as in addition yay manual installs of nvidia-dkms and rebuilds ran error free. Hopefully, the is some solution to it as this may detract even more novice people getting into Linux.

**Comment by killajoe** [comment]
It is selected automatically, but it let you unselect whatever you want and that can indeed lead into issues. 

In the end you need to learn these things to run arch based systems.
