### ISSUE TITLE
Chose an init system

### ISSUE THREAD

**Issue by l0s0s** [endeavouros-team/EndeavourOS-calamares#4]
I really like your installer, because, despite the fact that it uses a graphical interface, you can install what you really need, but it would be very cool if you could also choose an init system.

**Comment by killajoe** [comment]
We do provide an installer to basically install a minimal preconfigured Arch-Install and Archlinux supports systemd only:

_Warning: Arch Linux only has official support for systemd. [1] When using a different init system, please mention so in support requests._
source:
https://wiki.archlinux.org/title/Init
