### ISSUE TITLE
README.md  missing info on why we use custom packages module

### ISSUE THREAD

**Issue by killajoe** [endeavouros-team/EndeavourOS-calamares#51]
the info for packages and copy_kernel modules are still missing.
@dalto8

**Comment by dalto8** [comment]
I updated the packages module information.

As for copy_kernel, I don't know why we need to copy the kernel and initrd during an offline install but I don't think this module is being used.  It was replaced by a shell process at some point.

**Comment by killajoe** [comment]
> As for copy_kernel, I don't know why we need to copy the kernel and initrd during an offline install but I don't think this module is being used. It was replaced by a shell process at some point.

I see that's the reason why my head was empty on reason why in this case.. 
and indeed i remember now:
https://github.com/endeavouros-team/EndeavourOS-calamares/blob/1c82de3bc2e46bfa42cec60447429209419a0e2a/calamares/settings_offline.conf#L57

https://github.com/endeavouros-team/EndeavourOS-calamares/blob/main/calamares/modules/shellprocess_ck.conf
